# Generated by Django 5.2.6 on 2025-11-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
