# Generated by Django 5.2.6 on 2025-10-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='image',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='social_links/'),
        ),
    ]
