# Generated by Django 5.2.6 on 2025-11-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Get In Touch', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phones', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='sitecontent.contactsection')),
            ],
        ),
    ]
